src/AssetManagementPlatform.School/Entities/Teacher.cs
using System;
using AssetManagementPlatform.Core.DB.Entities;

namespace AssetManagementPlatform.SchoolModule.Entities
{
    public class Teacher : User
    {
        public DateTime DateOfBirth { get; set; }
    }
}

src/AssetManagementPlatform.School/ViewModels/Teacher/TeacherCreateModel.cs
using System;
using System.Collections.Generic;
using AssetManagementPlatform.SchoolModule.ViewModels.Shared;

namespace AssetManagementPlatform.SchoolModule.ViewModels.Teacher
{
    public class TeacherCreateModel
    {
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public DateTime DateOfBirth { get; set; }
        public IList<ItemSelection> ClassroomSelections { get; set; }
    }
}

src/AssetManagementPlatform.School/ViewModels/Teacher/TeacherDetailsModel.cs
using System.Collections.Generic;

namespace AssetManagementPlatform.SchoolModule.ViewModels.Teacher
{
    public class TeacherDetailsModel : TeacherCreateModel
    {
        public string FullName => $"{Firstname} {LastName}";
        public IList<Entities.Classroom> AssignedClassrooms { get; set; }
    }
}

src/AssetManagementPlatform.School/ViewModels/Teacher/TeacherEditModel.cs
using System;

namespace AssetManagementPlatform.SchoolModule.ViewModels.Teacher
{
    public class TeacherEditModel : TeacherCreateModel
    {
        public Guid Id { get; set; }
    }
}

src/AssetManagementPlatform.School/Controllers/ClassroomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AssetManagementPlatform.Core.Authorization.Extensions;
using AssetManagementPlatform.Core.Code;
using AssetManagementPlatform.Core.IdHelpers;
using AssetManagementPlatform.Core.Web;
using AssetManagementPlatform.SchoolModule.Code.Abstractions;
using AssetManagementPlatform.SchoolModule.Code.Authentication;
using AssetManagementPlatform.SchoolModule.Code.Authentication.Extensions;
using AssetManagementPlatform.SchoolModule.Code.IdHelpers;
using AssetManagementPlatform.SchoolModule.Code.SavingManagers;
using AssetManagementPlatform.SchoolModule.Entities;
using AssetManagementPlatform.SchoolModule.ViewModels.Classroom;
using AssetManagementPlatform.SchoolModule.ViewModels.Shared;
using Microsoft.AspNetCore.Mvc;

namespace AssetManagementPlatform.SchoolModule.Controllers
{
    public class ClassroomController : BaseController
    {
        private readonly IClassroomManager _classroomManager;
        private readonly IStudentManager _studentManager;
        private readonly ITeacherManager _teacherManager;

        public ClassroomController(SavingClassroomManager classroomManager, SavingStudentManager studentManager,
                                   SavingTeacherManager teacherManager)
        {
            _classroomManager = classroomManager;
            _studentManager = studentManager;
            _teacherManager = teacherManager;
        }

        public IActionResult Create()
        {
            ClassroomCreateModel model = new ClassroomCreateModel
            {
                StudentSelections = GetStudentOptions().ToList(),
                TeacherSelections = GetTeacherOptions().ToList()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(ClassroomCreateModel model)
        {
            var classroom = _classroomManager.Create(model.Name);
            ClassroomId classroomId = new ClassroomId(classroom.Id);

            if (model.StudentSelections != null)
                foreach (var student in model.StudentSelections.Where(i => i.IsSelected))
                {
                    UserId userId = new UserId(student.Id);
                    _classroomManager.Assign(userId, classroomId);
                }

            if (model.TeacherSelections != null)
                foreach (var teacher in model.TeacherSelections.Where(i => i.IsSelected))
                {
                    UserId userId = new UserId(teacher.Id);
                    _classroomManager.Assign(userId, classroomId);
                }

            return RedirectToAction("Index");
        }

        public ViewResult Details(Guid id)
        {
            ClassroomId classroomId = new ClassroomId(id);
            var classroom = _classroomManager.GetAllClassrooms().GetEntity(classroomId);
            var model = new ClassroomDetailsModel
            {
                Id = id,
                Name = classroom.Name,
                AssignedStudents = _classroomManager.GetStudentsInClass(classroomId).ToList(),
                AssignedTeachers = _classroomManager.GetTeachersInClass(classroomId).ToList(),
                AbsentStudentEvents = _classroomManager.GetStudentAbsentEvents(classroomId, DateTime.Now.AddDays(-30), DateTime.Today).ToList(),
            };
            return View(model);
        }

        public ViewResult Edit(Guid id)
        {
            ClassroomId classroomId = new ClassroomId(id);
            var classroom = _classroomManager.GetAllClassrooms().GetEntity(classroomId);
            var assignedStudents = _classroomManager.GetStudentsInClass(classroom);
            var assignedTeachers = _classroomManager.GetTeachersInClass(classroom);
            var model = new ClassroomEditModel
            {
                Id = classroom.Id,
                Name = classroom.Name,
                StudentSelections = GetStudentOptions()
                    .Select(i =>
                    {
                        i.IsSelected = assignedStudents.Any(s => s.Id == i.Id);
                        return i;
                    }).ToList(),
                TeacherSelections = GetTeacherOptions()
                    .Select(i =>
                    {
                        i.IsSelected = assignedTeachers.Any(s => s.Id == i.Id);
                        return i;
                    }).ToList()
            };
            return View(model);
        }

        [HttpPost]
        public RedirectToActionResult Edit(ClassroomEditModel model)
        {
            ClassroomId classroomId = new ClassroomId(model.Id);

            var classroom = _classroomManager.GetAllClassrooms().GetEntity(classroomId);
            var assignedStudents = _classroomManager.GetStudentsInClass(classroom);
            var assignedTeachers = _classroomManager.GetTeachersInClass(classroom);

            foreach (var studentSelection in model.StudentSelections)
            {
                UserId userId = new UserId(studentSelection.Id);
                if (studentSelection.IsSelected && !assignedStudents.Any(s => s.Id == studentSelection.Id))
                    _classroomManager.Assign(userId, classroomId);
                if (!studentSelection.IsSelected && assignedStudents.Any(s => s.Id == studentSelection.Id))
                    _classroomManager.UnAssign(userId, classroomId);
            }

            foreach (var teacherSelection in model.TeacherSelections)
            {
                UserId userId = new UserId(teacherSelection.Id);
                if (teacherSelection.IsSelected && !assignedTeachers.Any(s => s.Id == teacherSelection.Id))
                    _classroomManager.Assign(userId, classroomId);
                if (!teacherSelection.IsSelected && assignedTeachers.Any(s => s.Id == teacherSelection.Id))
                    _classroomManager.UnAssign(userId, classroomId);
            }

            classroom.Name = model.Name;

            _classroomManager.Edit(classroom);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(Guid id)
        {
            _classroomManager.Delete(new ClassroomId(id));
            return RedirectToAction("Index");
        }

        public IActionResult Index(string query)
        {
            IQueryable<Classroom> classroomQuery = _classroomManager.GetClassrooms(User.GetUserId());

            SchoolSitePermissions permissions = User.GetSchoolUserPermissions();
            if (permissions.SeeAllClasses)
                classroomQuery = _classroomManager.GetAllClassrooms();

            if (!permissions.SeeOwnClasses && !permissions.SeeAllClasses)
                return Unauthorized();

            if (!string.IsNullOrWhiteSpace(query))
                classroomQuery = classroomQuery.Where(a => a.Name.Contains(query, StringComparison.OrdinalIgnoreCase));



            return View(classroomQuery.ToList());
        }

        private IEnumerable<ItemSelection> GetStudentOptions()
        {
            return _studentManager.GetStudents()
                                  .Select(s => new ItemSelection
                                  {
                                      Id = s.Id,
                                      Name = s.FullName,
                                      IsSelected = false
                                  });
        }

        private IEnumerable<ItemSelection> GetTeacherOptions()
        {
            return _teacherManager.GetTeachers()
                                  .Select(t => new ItemSelection
                                  {
                                      Id = t.Id,
                                      Name = t.FullName,
                                      IsSelected = false
                                  });
        }

        public IActionResult MarkAbsence(Guid id, Guid studentId)
        {
            _studentManager.MarkAbsent(new StudentId(studentId), new ClassroomId(id));
            return RedirectToAction("Details", new { id = id });
        }

        public IActionResult UnmarkAbsense(Guid id, Guid studentId)
        {
            _studentManager.UnmarkAbsent(new EventId(studentId));
            return RedirectToAction("Details", new { id = id });
        }
    }
}

src/AssetManagementPlatform.School/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AssetManagementPlatform.Core.Authorization.Extensions;
using AssetManagementPlatform.Core.Code;
using AssetManagementPlatform.Core.DB.Entities;
using AssetManagementPlatform.Core.Web;
using AssetManagementPlatform.SchoolModule.Code.Abstractions;
using AssetManagementPlatform.SchoolModule.Code.Authentication;
using AssetManagementPlatform.SchoolModule.Code.Authentication.Extensions;
using AssetManagementPlatform.SchoolModule.Code.IdHelpers;
using AssetManagementPlatform.SchoolModule.Code.SavingManagers;
using AssetManagementPlatform.SchoolModule.Entities;
using AssetManagementPlatform.SchoolModule.ViewModels.Shared;
using AssetManagementPlatform.SchoolModule.ViewModels.Teacher;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TeacherEditModel = AssetManagementPlatform.SchoolModule.ViewModels.Teacher.TeacherEditModel;

namespace AssetManagementPlatform.SchoolModule.Controllers
{
    public class TeacherController : BaseController
    {
        private readonly ITeacherManager _teacherManager;
        private readonly IClassroomManager _classroomManager;

        public TeacherController(SavingTeacherManager teacherManager, SavingClassroomManager classroomManager)
        {
            _teacherManager = teacherManager;
            _classroomManager = classroomManager;
        }

        public IActionResult Index()
        {
            if (User.GetSchoolUserPermissions().IsStudent)
                return RedirectToAction("IndexStudent");

            if (User.GetSchoolUserPermissions().IsTeacher)
                return RedirectToAction("IndexTeacher");

            return Unauthorized();
        }

        [RoleAuthorizeSchool(nameof(SchoolSitePermissions.IsTeacher))]
        public ViewResult IndexTeacher(string query)
        {
            IQueryable<Teacher> teacherQuery = _teacherManager.GetTeachers();

            if (!string.IsNullOrWhiteSpace(query))
                teacherQuery = teacherQuery.Where(a =>
                                                      a.FirstName.Contains(query, StringComparison.OrdinalIgnoreCase) ||
                                                      a.LastName.Contains(query, StringComparison.OrdinalIgnoreCase));

            return View(teacherQuery.ToList());
        }

        public IActionResult IndexStudent(string query)
        {
            SchoolSitePermissions permissions = User.GetSchoolUserPermissions();
            if (permissions.IsTeacher)
                return RedirectToAction("IndexTeacher", new { query });

            var teacherQuery = _teacherManager.GetAssignedTeachers(new StudentId(User.GetUserId()));

            if (!string.IsNullOrWhiteSpace(query))
                teacherQuery = teacherQuery.Where(a =>
                                                      a.FirstName.Contains(query, StringComparison.OrdinalIgnoreCase) ||
                                                      a.LastName.Contains(query, StringComparison.OrdinalIgnoreCase));

            return View(teacherQuery.ToList());
        }

        public ViewResult Create()
        {
            return View(new TeacherCreateModel
            {
                ClassroomSelections = GetClassroomOptions().ToList()
            });
        }

        [HttpPost]
        public RedirectToActionResult Create(TeacherCreateModel createModel)
        {
            var teacher = _teacherManager.Create(createModel.Firstname, createModel.LastName, createModel.DateOfBirth);

            foreach (var selectedClassroom in createModel.ClassroomSelections.Where(x => x.IsSelected))
                _classroomManager.Assign(teacher, new ClassroomId(selectedClassroom.Id));

            return RedirectToAction("IndexStudent");
        }

        public IActionResult Delete(Guid id)
        {
            _teacherManager.Delete(new TeacherId(id));
            return RedirectToAction("IndexStudent");
        }

        public void Assign(Asset asset, Teacher teacher)
        {
            _teacherManager.Assign(asset, teacher);
        }

        public IActionResult Edit(Guid id)
        {
            TeacherId teacherId = new TeacherId(id);
            var teacher = _teacherManager.GetTeachers().GetEntity(teacherId);
            var assignedClassrooms = _classroomManager.GetClassrooms(teacher).ToList();
            return View(new TeacherEditModel
            {
                Id = teacher.Id,
                Firstname = teacher.FirstName,
                LastName = teacher.LastName,
                DateOfBirth = teacher.DateOfBirth,
                ClassroomSelections = GetClassroomOptions()
                    .Select(r =>
                    {
                        r.IsSelected = assignedClassrooms.Any(x => x.Id == r.Id);
                        return r;
                    }).ToList()
            });
        }

        [HttpPost]
        public RedirectToActionResult Edit(TeacherEditModel model)
        {
            TeacherId teacherId = new TeacherId(model.Id);
            var teacher = _teacherManager.GetTeachers().GetEntity(teacherId);
            var assignedClassrooms = _classroomManager.GetClassrooms(teacher).ToList();

            foreach (var classChoices in model.ClassroomSelections)
            {
                if (classChoices.IsSelected && !assignedClassrooms.Any(x => x.Id == classChoices.Id))
                    _classroomManager.Assign(teacher, new ClassroomId(classChoices.Id));

                if (!classChoices.IsSelected && assignedClassrooms.Any(x => x.Id == classChoices.Id))
                    _classroomManager.UnAssign(teacher, new ClassroomId(classChoices.Id));
            }

            teacher.FirstName = model.Firstname;
            teacher.LastName = model.LastName;
            teacher.DateOfBirth = model.DateOfBirth;

            _teacherManager.EditTeacher(teacher);
            return RedirectToAction("IndexStudent");
        }

        public IActionResult Details(Guid id)
        {
            TeacherId teacherId = new TeacherId(id);
            var teacher = _teacherManager.GetTeachers().GetEntity(teacherId);
            var assignedClassrooms = _classroomManager.GetClassrooms(teacher).ToList();

            return View(new TeacherDetailsModel
            {
                Firstname = teacher.FirstName,
                LastName = teacher.LastName,
                DateOfBirth = teacher.DateOfBirth,
                AssignedClassrooms = assignedClassrooms
            });
        }

        private IEnumerable<ItemSelection> GetClassroomOptions()
        {
            return _classroomManager.GetAllClassrooms()
                                    .Select(x => new ItemSelection
                                    {
                                        Id = x.Id,
                                        Name = x.Name,
                                        IsSelected = false
                                    });
        }
    }
}

src/AssetManagementPlatform.School/Views/Teacher/Create.cshtml
@model AssetManagementPlatform.SchoolModule.ViewModels.Teacher.TeacherCreateModel
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Create a new teacher
                </div>
                <div class="card-body">
                    <form asp-action="Create" method="post">
                        <div class="form-group">
                            <label>Firstname</label>
                            <input asp-for="Firstname" class="form-control" />
                            <span asp-validation-for="Firstname" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Lastname</label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Date of birth</label>
                            <input asp-for="DateOfBirth" type="date" class="form-control" />
                            <span asp-validation-for="DateOfBirth" type="date" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Classes</label>
                            @Html.EditorFor(x => x.ClassroomSelections)
                        </div>
                        <br />
                        <div class="form-group">
                            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                            <input type="submit" name="submit" value="Create" class="btn btn-success float-right" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/AssetManagementPlatform.School/Views/Teacher/Details.cshtml
@using AssetManagementPlatform.SchoolModule.Entities;
@model AssetManagementPlatform.SchoolModule.ViewModels.Teacher.TeacherDetailsModel

<div class="container-fluid">
    <div class="d-flex flex-column">
        <div class="p-2">
            <div class="card">
                <div class="card-body">
                    <h4>Teacher details</h4>
                    <div class="form-group">
                        <dl>
                            <dt>Name</dt>
                            <dd>@Model.FullName</dd>
                            @if (!string.IsNullOrWhiteSpace(Model.Address))
                            {
                                <dt>Address</dt>
                                <dd>@Model.Address</dd>
                            }
                            <dt>Date of birth</dt>
                            <dd>@Model.DateOfBirth.ToString("dd/MM/yyyy")</dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <div class="p-2">
            <div class="card">
                <div class="card-body">
                    <h4>Assigned classes</h4>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    Class name
                                </th>
                            </tr>
                        </thead>
                       <tbody>
                           @foreach (Classroom item in Model.AssignedClassrooms.OrderBy(a => a.Name)) 
                           {
                               <tr>
                                   <td>
                                       <a asp-controller="Classroom" asp-action="Details" asp-route-id="@item.Id">@item.Name</a>
                                   </td>
                               </tr>
                           }
                       </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

src/AssetManagementPlatform.School/Views/Teacher/Edit.cshtml
@model AssetManagementPlatform.SchoolModule.ViewModels.Teacher.TeacherEditModel

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Edit student
                </div>
                <div class="card-body">
                    <form asp-action="Edit" method="post" asp-antiforgery="true">
                        <div class="form-group">
                            <label>Firstname</label>
                            <input asp-for="Firstname" class="form-control" />
                            <span asp-validation-for="Firstname" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Lastname</label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Date of birth</label>
                            <input asp-for="DateOfBirth" type="date" class="form-control" />
                            <span asp-validation-for="DateOfBirth" type="date" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Classes</label>
                            @Html.EditorFor(x => x.ClassroomSelections)
                        </div>
                        <br />
                        <div class="form-group">
                            <a asp-action="IndexStudent" class="btn btn-secondary">Cancel</a>
                            <input type="submit" name="submit" value="Create" class="btn btn-success float-right" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/AssetManagementPlatform.School/Views/Teacher/IndexStudent.cshtml
@using AssetManagementPlatform.SchoolModule.Code.Authentication.Extensions
@using AssetManagementPlatform.SchoolModule.Entities
@model IEnumerable<AssetManagementPlatform.SchoolModule.Entities.Teacher>

@{
    ViewData["Title"] = "Index";
}
@{
    var permissions = User.GetSchoolUserPermissions();
}

<h1>Your teachers</h1>

<form method="get" asp-action="IndexTeacher">
    <div class="input-group">
        @Html.TextBox("query", "", new { @class = "form-control", placeholder = "Søg" })
    <span class="input-group-append">
        <button class="btn btn-primary">Søg</button>
    </span>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Firstname
            </th>
            <th>
                Lastname
            </th>
            <th>
                Date of birth
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (Teacher item in Model.OrderBy(a => a.FirstName))
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">@item.FirstName</a>
                </td>
                <td>
                    @item.LastName
                </td>
                <td>
                    @item.DateOfBirth.ToString("dd/MM/yyyy")
                </td>
            </tr>
        }
    </tbody>
</table>

src/AssetManagementPlatform.School/Views/Teacher/IndexTeacher.cshtml
@using AssetManagementPlatform.SchoolModule.Code.Authentication.Extensions
@using AssetManagementPlatform.SchoolModule.Entities
@model IEnumerable<AssetManagementPlatform.SchoolModule.Entities.Teacher>

@{
    ViewData["Title"] = "Index";
}
@{
    var permissions = User.GetSchoolUserPermissions();
}

<a class="btn btn-sm btn-success float-right" asp-action="Create">Create teacher</a>
<h1>Teachers</h1>

<form method="get" asp-action="IndexTeacher">
    <div class="input-group">
        @Html.TextBox("query", "", new { @class = "form-control", placeholder = "Søg" })
        <span class="input-group-append">
            <button class="btn btn-primary">Søg</button>
        </span>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Firstname
            </th>
            <th>
                Lastname
            </th>
            <th>
                Date of birth
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Teacher item in Model.OrderBy(a => a.FirstName))
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">@item.FirstName</a>
                </td>
                <td>
                    @item.LastName
                </td>
                <td>
                    @item.DateOfBirth.ToString("dd/MM/yyyy")
                </td>
                <td class="text-nowrap">
                    <a class="btn btn-sm btn-warning @(permissions.EditTeacher ? "" : "disabled")" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-sm btn-danger @(permissions.DeleteTeacher ? "" : "disabled")" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>