src/AssetManagementPlatform.Construction/ViewModels/Reservation/Model/ReservationModel.cs
using AssetManagementPlatform.Core.DB.Entities.Events;

namespace AssetManagementPlatform.ConstructionModule.ViewModels.Reservation.Model
{
    public class ReservationModel
    {
        public ReservationEvent ReservationEvent { get; set; }
        public Entities.Tool Tool { get; set; }
    }
}

src/AssetManagementPlatform.Construction/ViewModels/Reservation/ReservationCreateModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AssetManagementPlatform.ConstructionModule.ViewModels.Reservation
{
    public class ReservationCreateModel
    {
        public IList<SelectListItem> ReservedToOptions { get; set; }
        public IList<SelectListItem> ReservedAssetOptions { get; set; }

        public Guid ReservedToId { get; set; }
        public Guid ReservedAssetId { get; set; }

        [Required]
        public DateTime ReservationStartDate { get; set; }

        [Required]
        public DateTime ReservationEndDate { get; set; }
    }
}

src/AssetManagementPlatform.Construction/ViewModels/Reservation/ReservationEditModel.cs
using System;

namespace AssetManagementPlatform.ConstructionModule.ViewModels.Reservation
{
    public class ReservationEditModel : ReservationCreateModel
    {
        public Guid Id { get; set; }
    }
}

src/AssetManagementPlatform.Construction/ViewModels/Reservation/ReservationIndexModel.cs
using System.Collections.Generic;
using AssetManagementPlatform.ConstructionModule.ViewModels.Reservation.Model;

namespace AssetManagementPlatform.ConstructionModule.ViewModels.Reservation
{
    public class ReservationIndexModel
    {
        public ReservationIndexModel()
        {
            Reservations = new List<ReservationModel>();
        }

        public List<ReservationModel> Reservations { get; set; }
    }
}

src/AssetManagementPlatform.Construction/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AssetManagementPlatform.ConstructionModule.Code.Interfaces;
using AssetManagementPlatform.ConstructionModule.Code.SavingManagers;
using AssetManagementPlatform.ConstructionModule.Entities;
using AssetManagementPlatform.ConstructionModule.ViewModels.Reservation;
using AssetManagementPlatform.ConstructionModule.ViewModels.Reservation.Model;
using AssetManagementPlatform.Core.Abstractions.Managers;
using AssetManagementPlatform.Core.Code;
using AssetManagementPlatform.Core.DB.Entities.Events;
using AssetManagementPlatform.Core.IdHelpers;
using AssetManagementPlatform.Core.SavingManagers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AssetManagementPlatform.ConstructionModule.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IReservationManager _reservationManager;
        private readonly IToolManager _toolManager;
        private readonly IUserManager _userManager;

        public ReservationController(SavingReservationManager reservationManager, SavingToolManager toolManager, SavingUserManager userManager)
        {
            _reservationManager = reservationManager;
            _toolManager = toolManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            ReservationIndexModel indexModel = new ReservationIndexModel();
            var reservationEvents = _reservationManager.GetReservationEvents();
            indexModel.Reservations = reservationEvents
                                      .Include(a => a.ReservedAsset)
                                      .Include(a => a.ReservedTo)
                                      .Where(a => a.IsActive)
                                      .Select(x => new ReservationModel
                                      {
                                          ReservationEvent = x,
                                          Tool = (Tool)x.ReservedAsset
                                      })
                                      .ToList();

            return View(indexModel);
        }

        public IActionResult Create()
        {
            ReservationCreateModel createModel = new ReservationCreateModel();
            createModel.ReservedToOptions = GetReservedToOptions();
            createModel.ReservedAssetOptions = GetReservedAssetOptions();
            return View(createModel);
        }

        [HttpPost]
        public IActionResult Create(ReservationCreateModel createModel)
        {
            AssetId reservedTo = new AssetId(createModel.ReservedToId);
            AssetId reservedAsset = new AssetId(createModel.ReservedAssetId);
            _reservationManager.CreateReservation(createModel.ReservationStartDate, createModel.ReservationEndDate, reservedTo, reservedAsset);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(Guid id)
        {
            ReservationEditModel editModel = new ReservationEditModel();
            ReservationEvent reservationEvent = _reservationManager.GetReservationEvents().GetEntity(new EventId(id));

            editModel.ReservationStartDate = reservationEvent.ReservationStartDate;
            editModel.ReservationEndDate = reservationEvent.ReservationEndDate;

            editModel.ReservedToOptions = GetReservedToOptions()
                .Select(r =>
                {
                    r.Selected = reservationEvent.ReservedToId.ToString() == r.Value;
                    return r;
                }).ToList();
            editModel.ReservedAssetOptions = GetReservedAssetOptions()
                .Select(r =>
                {
                    r.Selected = reservationEvent.ReservedAssetId.ToString() == r.Value;
                    return r;
                }).ToList();
            return View(editModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ReservationEditModel editModel)
        {
            _reservationManager.CancelReservation(new EventId(editModel.Id));
            AssetId reservedTo = new AssetId(editModel.ReservedToId);
            AssetId reservedAsset = new AssetId(editModel.ReservedAssetId);
            _reservationManager.CreateReservation(editModel.ReservationStartDate, editModel.ReservationEndDate, reservedTo, reservedAsset);
            return RedirectToAction("Index");
        }

        private List<SelectListItem> GetReservedAssetOptions()
        {
            List<SelectListItem> reservedAssetOptions = _toolManager.GetTools()
                                                                    .Select(a => new SelectListItem($"{a.Manufacture}, {a.Model}", a.Id.ToString()))
                                                                    .ToList();

            return reservedAssetOptions;
        }

        private List<SelectListItem> GetReservedToOptions()
        {
            List<SelectListItem> reservedToOptions = _userManager.GetUsers()
                                                                 .Select(a => new SelectListItem(a.FullName, a.Id.ToString()))
                                                                 .ToList();

            return reservedToOptions;
        }

        public IActionResult Delete(Guid id)
        {
            _reservationManager.CancelReservation(new EventId(id));
            return RedirectToAction("Index");
        }
    }
}

src/AssetManagementPlatform.Construction/Controllers/ToolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AssetManagementPlatform.ConstructionModule.Code.Authentication;
using AssetManagementPlatform.ConstructionModule.Code.Authentication.Extensions;
using AssetManagementPlatform.ConstructionModule.Code.IdHelpers;
using AssetManagementPlatform.ConstructionModule.Code.Interfaces;
using AssetManagementPlatform.ConstructionModule.Code.SavingManagers;
using AssetManagementPlatform.ConstructionModule.ViewModels.Tool;
using AssetManagementPlatform.ConstructionModule.ViewModels.Tool.Model;
using AssetManagementPlatform.Core.Abstractions.Managers;
using AssetManagementPlatform.Core.Authorization.Extensions;
using AssetManagementPlatform.Core.Code;
using AssetManagementPlatform.Core.DB.Entities.Events;
using AssetManagementPlatform.Core.IdHelpers;
using AssetManagementPlatform.Core.SavingManagers;
using AssetManagementPlatform.Core.Web;
using JKang.EventBus;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AssetManagementPlatform.ConstructionModule.Controllers
{
    public class ToolController : BaseController
    {
        private readonly IAssetManager _assetManager;
        private readonly IEventManager _eventManager;
        private readonly IEventPublisher _eventPublisher;
        private readonly IProjectManager _projectManager;
        private readonly IToolManager _toolManager;
        private readonly IOrganizationManager _organizationManager;
        private readonly IUserManager _userManager;

        public ToolController(SavingToolManager toolManager,
                              SavingOrganizationManager organizationManager,
                              SavingEventManager eventManager,
                              SavingUserManager userManager,
                              IEventPublisher eventPublisher,
                              SavingAssetManager assetManager,
                              SavingProjectManager projectManager)
        {
            _toolManager = toolManager;
            _organizationManager = organizationManager;
            _eventManager = eventManager;
            _eventPublisher = eventPublisher;
            _assetManager = assetManager;
            _projectManager = projectManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> IndexAdmin(string query)
        {

            var toolQuery = _toolManager.GetTools();

            if (!string.IsNullOrWhiteSpace(query))
                toolQuery = toolQuery.Where(a => a.Model.Contains(query, StringComparison.OrdinalIgnoreCase) ||
                                                 a.Manufacture.Contains(query, StringComparison.OrdinalIgnoreCase));

            var tools = await toolQuery.ToListAsync();

            var toolModels = new List<ToolModel>();
            foreach (var tool in tools)
                toolModels.Add(new ToolModel
                {
                    Tool = tool,
                    AssignedUser = _toolManager.GetUserAssignedToTool(tool)
                });

            return View(toolModels);
        }

        public async Task<IActionResult> Index(string query)
        {
            var permissions = User.GetUserPermissions();
            if (permissions.IsAdmin)
                return RedirectToAction("IndexAdmin", new { query });

            var toolQuery = _toolManager.GetTools();

            if (!string.IsNullOrWhiteSpace(query))
                toolQuery = toolQuery.Where(a =>
                                                a.Model.Contains(query, StringComparison.OrdinalIgnoreCase) ||
                                                a.Manufacture.Contains(query, StringComparison.OrdinalIgnoreCase));

            var tools = await toolQuery.ToListAsync();

            var toolModels = new List<ToolModel>();
            foreach (var tool in tools)
                toolModels.Add(new ToolModel
                {
                    Tool = tool,
                    AssignedUser = _toolManager.GetUserAssignedToTool(tool),
                    RequestEvents = _toolManager.GetAssignmentRequests(tool).Include(x => x.RequestingUser).ToList(),
                    RepairEvents = _toolManager.GetRepairRequests(tool).Include(x => x.ReportedByUser).ToList()
                });
            return View(toolModels);
        }

        [RoleAuthorizeConstruction(nameof(ConstructionSitePermissions.CanCreateTool))]
        public IActionResult Create()
        {
            var user = User.GetUserId();
            var userOptions = new List<SelectListItem>();
            if (user != null)
                userOptions = GetUserOptions()
                              .Select(x =>
                              {
                                  x.Selected = user.Id.ToString() == x.Value;
                                  return x;
                              })
                              .ToList();
            ToolCreateModel model = new ToolCreateModel
            {
                UserOptions = userOptions
            };
            return View(model);
        }

        [RoleAuthorizeConstruction(nameof(ConstructionSitePermissions.CanCreateTool))]
        [HttpPost]
        public IActionResult Create(ToolCreateModel createModel)
        {
            var tool = _toolManager.CreateTool(createModel.Model, createModel.Manufacture, createModel.Price);
            _organizationManager.AssignAssetToOrganization(tool, User.GetUserOrganizationId());
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var tool = await _toolManager.GetTools().GetEntityAsync(new ToolId(id));

            var assignedUser = _toolManager.GetUserAssignedToTool(tool);

            // You should not be able to access other tools than your own on less you may see all tools.
            if (!User.GetConstructionUserPermissions().CanSeeAllTools &&
                assignedUser != null &&
                assignedUser.Id != User.GetUserId().Id)
                return Unauthorized();

            var eventsByAsset = _eventManager.GetEventsByAsset(tool);

            var brokenEvents = _toolManager.GetRepairRequests(tool)
                                           .Include(x => x.ReportedByUser)
                                           .ToList();
            var model = new ToolDetailsModel
            {
                Id = tool.Id,
                Model = tool.Model,
                Manufacture = tool.Manufacture,
                Price = tool.Price,
                Events = eventsByAsset.ToList(),
                AssignedUser = assignedUser,
                CreatedOn = tool.CreatedOn,
                UpdatedOn = tool.UpdatedOn,
                BrokenEvents = brokenEvents
            };

            return View(model);
        }

        [RoleAuthorizeConstruction(nameof(ConstructionSitePermissions.CanDeleteTool))]
        public async Task<ActionResult> Delete(Guid id)
        {
            var toolId = new ToolId(id);
            var tool = await _toolManager.GetTools().GetEntityAsync(toolId);

            var assignedUser = _toolManager.GetUserAssignedToTool(tool);

            // You should not be able to access other tools than your own on less you may see all tools.
            if (!User.GetConstructionUserPermissions().CanSeeAllTools &&
                assignedUser != null &&
                assignedUser.Id != User.GetUserId().Id)
                return Unauthorized();

            _toolManager.RemoveTool(toolId);
            return RedirectToAction("Index");
        }

        public ViewResult Edit(Guid id)
        {
            ToolId toolId = new ToolId(id);

            var tool = _toolManager.GetTools().GetEntity(toolId);
            var user = _toolManager.GetUserAssignedToTool(toolId);
            var userOptions = new List<SelectListItem>();

            // If the tool is assigned a user
            if (user != null)
            {
                userOptions = GetUserOptions()
                              .Select(x =>
                              {
                                  x.Selected = user.Id.ToString() == x.Value;
                                  return x;
                              })
                              .ToList();
            }

            List<SelectListItem> projectOptions = _projectManager.GetProjectsByOrganization(User.GetUserOrganizationId())
                                                                 .Select(a => new SelectListItem(a.Name, a.Id.ToString(), a.Id == tool.ProjectId))
                                                                 .ToList();
            projectOptions.Add(new SelectListItem("-----", string.Empty, user == null));

            return View(new ToolEditModel
            {
                Model = tool.Model,
                Manufacture = tool.Manufacture,
                Price = tool.Price,
                ProjectOptions = projectOptions,
                UserOptions = userOptions
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ToolEditModel editModel)
        {
            if (!ModelState.IsValid)
                return View(editModel);

            var toolId = new ToolId(editModel.Id);
            var tool = _toolManager.GetTools().GetEntity(toolId);

            tool.Model = editModel.Model;
            tool.Manufacture = editModel.Manufacture;
            tool.Price = editModel.Price;
            tool.ProjectId = editModel.SelectedProjectId;
            var assignmentEvent = _eventManager.GetEventsByType<AssignmentEvent>().LastOrDefault(t => t.AssetId == toolId.Id);
            if (assignmentEvent != null && assignmentEvent.AssignedUserId == editModel.SelectedUserId)
            {
                _toolManager.EditTool(tool);
                return RedirectToAction("Index");
            }

src/AssetManagementPlatform.Construction/Views/Reservation/Create.cshtml
@model AssetManagementPlatform.ConstructionModule.ViewModels.Reservation.ReservationCreateModel

@{
    ViewData["Title"] = "Create reservation";
}

<div class="card">
    <div class="card-header">
        Create a reservation
    </div>
    <div class="card-body">
        <form asp-action="Create" method="post" asp-antiforgery="true">
            <div class="form-group">
                <label>Reserved to</label>
                <select asp-items="@Model.ReservedToOptions" name="@nameof(Model.ReservedToId)" class="form-control"></select>
                <span asp-validation-for="ReservedToId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Reserved asset</label>
                <select asp-items="@Model.ReservedAssetOptions" name="@nameof(Model.ReservedAssetId)" class="form-control"></select>
                <span asp-validation-for="ReservedAssetId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Reservation start date</label>
                <input asp-for="ReservationStartDate" class="form-control" />
                <span asp-validation-for="ReservationStartDate" type="date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Reservation end date</label>
                <input asp-for="ReservationEndDate" class="form-control" />
                <span asp-validation-for="ReservationEndDate" type="date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                <input type="submit" name="submit" value="Create" class="btn btn-success float-right" />
            </div>
        </form>
    </div>
</div>

src/AssetManagementPlatform.Construction/Views/Reservation/Edit.cshtml
@model AssetManagementPlatform.ConstructionModule.ViewModels.Reservation.ReservationEditModel
@{
    ViewData["Title"] = "Edit reservation";
}
<h1>Reservation</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Edit a reservation
                </div>
                <div class="card-body">
                    <form asp-action="Edit" method="post" asp-antiforgery="true">
                        <div class="form-group">
                            <label>Reserved to</label>
                            <select asp-items="@Model.ReservedToOptions" name="@nameof(Model.ReservedToId)" class="form-control"></select>
                            <span asp-validation-for="ReservedToId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Reserved asset</label>
                            <select asp-items="@Model.ReservedAssetOptions" name="@nameof(Model.ReservedAssetId)" class="form-control"></select>
                            <span asp-validation-for="ReservedAssetId" type="date" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Reservation end date</label>
                            <input asp-for="ReservationEndDate" class="form-control" />
                            <span asp-validation-for="ReservationEndDate" type="date" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                            <input type="submit" name="submit" value="Edit" class="btn btn-success float-right" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/AssetManagementPlatform.Construction/Views/Reservation/Index.cshtml
@using AssetManagementPlatform.ConstructionModule.ViewModels.Reservation.Model
@model AssetManagementPlatform.ConstructionModule.ViewModels.Reservation.ReservationIndexModel
@{
    ViewData["Title"] = "Reservations";
}

<a class="btn btn-sm btn-success float-right" asp-action="Create">Create reservation</a>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">
                Reservations
            </div>
            <div class="card-body">
                @if (Model.Reservations.Any())
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Model</th>
                                <th>Manufacture</th>
                                <th>Reserved from</th>
                                <th>Reserved to</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>

                        @foreach (ReservationModel reservationModel in Model.Reservations)
                        {
                            <tr>
                                <td>
                                    <a asp-controller="Tool" asp-action="Details" asp-route-id="@reservationModel.Tool.Id">@reservationModel.Tool.Model</a>
                                </td>
                                <td>
                                    @reservationModel.Tool.Manufacture
                                </td>
                                <td>
                                    @reservationModel.ReservationEvent.ReservationStartDate.ToString("dd/MM/yyyy")
                                </td>
                                <td>
                                    @reservationModel.ReservationEvent.ReservationEndDate.ToString("dd/MM/yyyy")
                                </td>
                                <td class="text-nowrap">
                                    <a class="btn btn-sm btn-warning" asp-action="Edit" asp-route-id="@reservationModel.ReservationEvent.Id">Edit</a>
                                    <a class="btn btn-sm btn-danger" asp-action="Delete" asp-route-id="@reservationModel.ReservationEvent.Id">Delete</a>
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                }
                else
                {
                    <span>No active reservations</span>
                }
            </div>
        </div>

    </div>
</div>