src/AssetManagementPlatform.School/Entities/Classroom.cs
using AssetManagementPlatform.Core.DB.Entities;

namespace AssetManagementPlatform.SchoolModule.Entities
{
    public class Classroom : AssetGroup
    {
    }
}

src/AssetManagementPlatform.School/ViewModels/Classroom/ClassroomCreateModel.cs
using System.Collections.Generic;
using AssetManagementPlatform.SchoolModule.ViewModels.Shared;

namespace AssetManagementPlatform.SchoolModule.ViewModels.Classroom
{
    public class ClassroomCreateModel
    {
        public string Name { get; set; }
        public IList<ItemSelection> StudentSelections { get; set; }
        public IList<ItemSelection> TeacherSelections { get; set; }
    }
}

src/AssetManagementPlatform.School/ViewModels/Classroom/ClassroomDetailsModel.cs
using System;
using System.Collections.Generic;
using AssetManagementPlatform.SchoolModule.Entities.Events;

namespace AssetManagementPlatform.SchoolModule.ViewModels.Classroom
{
    public class ClassroomDetailsModel : ClassroomCreateModel
    {
        public Guid Id { get; set; }
        public IList<Entities.Student> AssignedStudents { get; set; }
        public IList<StudentAbsentEvent> AbsentStudentEvents { get; set; }
        public IList<Entities.Teacher> AssignedTeachers { get; set; }
    }
}

src/AssetManagementPlatform.School/ViewModels/Classroom/ClassroomEditModel.cs
using System;

namespace AssetManagementPlatform.SchoolModule.ViewModels.Classroom
{
    public class ClassroomEditModel : ClassroomCreateModel
    {
        public Guid Id { get; set; }
    }
}

src/AssetManagementPlatform.School/ViewModels/Classroom/Model/AbsentModel.cs
using System.Collections.Generic;
using AssetManagementPlatform.SchoolModule.Code.IdHelpers;
using AssetManagementPlatform.SchoolModule.Entities.Events;

namespace AssetManagementPlatform.SchoolModule.ViewModels.Classroom.Model
{
    public class AbsentModel
    {
        public Entities.Student Student { get; set; }
        public StudentId StudentId { get; set; }
        public IList<StudentAbsentEvent> AbsentEvents { get; set; }
    }
}

src/AssetManagementPlatform.School/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AssetManagementPlatform.Core.Code;
using AssetManagementPlatform.Core.Web;
using AssetManagementPlatform.SchoolModule.Code.Abstractions;
using AssetManagementPlatform.SchoolModule.Code.IdHelpers;
using AssetManagementPlatform.SchoolModule.Code.SavingManagers;
using AssetManagementPlatform.SchoolModule.Entities;
using AssetManagementPlatform.SchoolModule.ViewModels.Shared;
using AssetManagementPlatform.SchoolModule.ViewModels.Student;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AssetManagementPlatform.SchoolModule.Controllers
{
    public class StudentController : BaseController
    {
        private readonly IStudentManager _studentManager;
        private readonly IClassroomManager _classroomManager;

        public StudentController(SavingStudentManager studentManager, SavingClassroomManager classroomManager)
        {
            _studentManager = studentManager;
            _classroomManager = classroomManager;
        }

        public ViewResult Index(string query)
        {
            IQueryable<Student> studentQuery = _studentManager.GetStudents();

            if (!string.IsNullOrWhiteSpace(query))
                studentQuery = studentQuery.Where(a =>
                                                      a.FirstName.Contains(query, StringComparison.OrdinalIgnoreCase) ||
                                                      a.LastName.Contains(query, StringComparison.OrdinalIgnoreCase));

            return View(studentQuery.ToList());
        }

        public ViewResult Create()
        {
            var model = new StudentCreateModel
            {
                ClassroomSelections = GetClassroomOptions().ToList()
            };
            return View(model);
        }

        [HttpPost]
        public RedirectToActionResult Create(StudentCreateModel model)
        {
            var student = _studentManager.CreateStudent(model.Firstname, model.LastName, model.DateOfBirth);

            foreach (var selectedClassroom in model.ClassroomSelections.Where(x => x.IsSelected))
                _classroomManager.Assign(student, new ClassroomId(selectedClassroom.Id));

            return RedirectToAction("Index");
        }

        public ViewResult Details(Guid id)
        {
            StudentId studentId = new StudentId(id);
            var student = _studentManager.GetStudents().GetEntity(studentId);
            var assignedClassrooms = _classroomManager.GetClassrooms(student).ToList();

            var detailsModel = new StudentDetailsModel
            {
                Firstname = student.FirstName,
                LastName = student.LastName,
                DateOfBirth = student.DateOfBirth,
                AssignedClassrooms = assignedClassrooms,
                AbsentStudentEvents = _studentManager.GetStudentAbsentEvents(studentId, DateTime.Now.AddDays(-30), DateTime.Today).ToList(),
            };
            return View(detailsModel);
        }

        public ViewResult Edit(Guid id)
        {
            StudentId studentId = new StudentId(id);
            var student = _studentManager.GetStudents().GetEntity(studentId);
            var assignedClassrooms = _classroomManager.GetClassrooms(student);
            var model = new StudentEditModel
            {
                Id = student.Id,
                Firstname = student.FirstName,
                LastName = student.LastName,
                DateOfBirth = student.DateOfBirth,
                ClassroomSelections = GetClassroomOptions()
                    .Select(r =>
                    {
                        r.IsSelected = assignedClassrooms.Any(x => x.Id == r.Id);
                        return r;
                    }).ToList()
            };
            return View(model);
        }

        [HttpPost]
        public RedirectToActionResult Edit(StudentEditModel model)
        {
            StudentId studentId = new StudentId(model.Id);
            var student = _studentManager.GetStudents().GetEntity(studentId);

            var assignedClassrooms = _classroomManager.GetClassrooms(student);

            foreach (var classChoices in model.ClassroomSelections)
            {
                ClassroomId classroomId = new ClassroomId(classChoices.Id);

                if (classChoices.IsSelected && !assignedClassrooms.Any(x => x.Id == classChoices.Id))
                    _classroomManager.Assign(student, classroomId);

                if (!classChoices.IsSelected && assignedClassrooms.Any(x => x.Id == classChoices.Id))
                    _classroomManager.UnAssign(student, classroomId);
            }

            student.FirstName = model.Firstname;
            student.LastName = model.LastName;
            student.DateOfBirth = model.DateOfBirth;

            _studentManager.EditStudent(student);
            return RedirectToAction("Index");
        }

        public RedirectToActionResult Delete(Guid id)
        {
            _studentManager.DeleteStudent(new StudentId(id));
            return RedirectToAction("Index");
        }

        private IEnumerable<ItemSelection> GetClassroomOptions()
        {
            return _classroomManager.GetAllClassrooms()
                                    .Select(x => new ItemSelection
                                    {
                                        Id = x.Id,
                                        Name = x.Name,
                                        IsSelected = false
                                    });
        }

        public RedirectToActionResult AssignBook(Guid book, Guid student)
        {
            _studentManager.AssignBook(new BookId(book), new StudentId(student));
            return RedirectToAction("Index");
        }
    }
}

src/AssetManagementPlatform.School/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AssetManagementPlatform.Core.Authorization.Extensions;
using AssetManagementPlatform.Core.Code;
using AssetManagementPlatform.Core.DB.Entities;
using AssetManagementPlatform.Core.Web;
using AssetManagementPlatform.SchoolModule.Code.Abstractions;
using AssetManagementPlatform.SchoolModule.Code.Authentication;
using AssetManagementPlatform.SchoolModule.Code.Authentication.Extensions;
using AssetManagementPlatform.SchoolModule.Code.IdHelpers;
using AssetManagementPlatform.SchoolModule.Code.SavingManagers;
using AssetManagementPlatform.SchoolModule.Entities;
using AssetManagementPlatform.SchoolModule.ViewModels.Shared;
using AssetManagementPlatform.SchoolModule.ViewModels.Teacher;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TeacherEditModel = AssetManagementPlatform.SchoolModule.ViewModels.Teacher.TeacherEditModel;

namespace AssetManagementPlatform.SchoolModule.Controllers
{
    public class TeacherController : BaseController
    {
        private readonly ITeacherManager _teacherManager;
        private readonly IClassroomManager _classroomManager;

        public TeacherController(SavingTeacherManager teacherManager, SavingClassroomManager classroomManager)
        {
            _teacherManager = teacherManager;
            _classroomManager = classroomManager;
        }

        public IActionResult Index()
        {
            if (User.GetSchoolUserPermissions().IsStudent)
                return RedirectToAction("IndexStudent");

            if (User.GetSchoolUserPermissions().IsTeacher)
                return RedirectToAction("IndexTeacher");

            return Unauthorized();
        }

        [RoleAuthorizeSchool(nameof(SchoolSitePermissions.IsTeacher))]
        public ViewResult IndexTeacher(string query)
        {
            IQueryable<Teacher> teacherQuery = _teacherManager.GetTeachers();

            if (!string.IsNullOrWhiteSpace(query))
                teacherQuery = teacherQuery.Where(a =>
                                                      a.FirstName.Contains(query, StringComparison.OrdinalIgnoreCase) ||
                                                      a.LastName.Contains(query, StringComparison.OrdinalIgnoreCase));

            return View(teacherQuery.ToList());
        }

        public IActionResult IndexStudent(string query)
        {
            SchoolSitePermissions permissions = User.GetSchoolUserPermissions();
            if (permissions.IsTeacher)
                return RedirectToAction("IndexTeacher", new { query });

            var teacherQuery = _teacherManager.GetAssignedTeachers(new StudentId(User.GetUserId()));

            if (!string.IsNullOrWhiteSpace(query))
                teacherQuery = teacherQuery.Where(a =>
                                                      a.FirstName.Contains(query, StringComparison.OrdinalIgnoreCase) ||
                                                      a.LastName.Contains(query, StringComparison.OrdinalIgnoreCase));

            return View(teacherQuery.ToList());
        }

        public ViewResult Create()
        {
            return View(new TeacherCreateModel
            {
                ClassroomSelections = GetClassroomOptions().ToList()
            });
        }

        [HttpPost]
        public RedirectToActionResult Create(TeacherCreateModel createModel)
        {
            var teacher = _teacherManager.Create(createModel.Firstname, createModel.LastName, createModel.DateOfBirth);

            foreach (var selectedClassroom in createModel.ClassroomSelections.Where(x => x.IsSelected))
                _classroomManager.Assign(teacher, new ClassroomId(selectedClassroom.Id));

            return RedirectToAction("IndexStudent");
        }

        public IActionResult Delete(Guid id)
        {
            _teacherManager.Delete(new TeacherId(id));
            return RedirectToAction("IndexStudent");
        }

        public void Assign(Asset asset, Teacher teacher)
        {
            _teacherManager.Assign(asset, teacher);
        }

        public IActionResult Edit(Guid id)
        {
            TeacherId teacherId = new TeacherId(id);
            var teacher = _teacherManager.GetTeachers().GetEntity(teacherId);
            var assignedClassrooms = _classroomManager.GetClassrooms(teacher).ToList();
            return View(new TeacherEditModel
            {
                Id = teacher.Id,
                Firstname = teacher.FirstName,
                LastName = teacher.LastName,
                DateOfBirth = teacher.DateOfBirth,
                ClassroomSelections = GetClassroomOptions()
                    .Select(r =>
                    {
                        r.IsSelected = assignedClassrooms.Any(x => x.Id == r.Id);
                        return r;
                    }).ToList()
            });
        }

        [HttpPost]
        public RedirectToActionResult Edit(TeacherEditModel model)
        {
            TeacherId teacherId = new TeacherId(model.Id);
            var teacher = _teacherManager.GetTeachers().GetEntity(teacherId);
            var assignedClassrooms = _classroomManager.GetClassrooms(teacher).ToList();

            foreach (var classChoices in model.ClassroomSelections)
            {
                if (classChoices.IsSelected && !assignedClassrooms.Any(x => x.Id == classChoices.Id))
                    _classroomManager.Assign(teacher, new ClassroomId(classChoices.Id));

                if (!classChoices.IsSelected && assignedClassrooms.Any(x => x.Id == classChoices.Id))
                    _classroomManager.UnAssign(teacher, new ClassroomId(classChoices.Id));
            }

            teacher.FirstName = model.Firstname;
            teacher.LastName = model.LastName;
            teacher.DateOfBirth = model.DateOfBirth;

            _teacherManager.EditTeacher(teacher);
            return RedirectToAction("IndexStudent");
        }

        public IActionResult Details(Guid id)
        {
            TeacherId teacherId = new TeacherId(id);
            var teacher = _teacherManager.GetTeachers().GetEntity(teacherId);
            var assignedClassrooms = _classroomManager.GetClassrooms(teacher).ToList();

            return View(new TeacherDetailsModel
            {
                Firstname = teacher.FirstName,
                LastName = teacher.LastName,
                DateOfBirth = teacher.DateOfBirth,
                AssignedClassrooms = assignedClassrooms
            });
        }

        private IEnumerable<ItemSelection> GetClassroomOptions()
        {
            return _classroomManager.GetAllClassrooms()
                                    .Select(x => new ItemSelection
                                    {
                                        Id = x.Id,
                                        Name = x.Name,
                                        IsSelected = false
                                    });
        }
    }
}

src/AssetManagementPlatform.School/Views/Classroom/Create.cshtml
@model AssetManagementPlatform.SchoolModule.ViewModels.Classroom.ClassroomCreateModel

<h1>Classes</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Create a class
                </div>
                <div class="card-body">
                    <form asp-action="Create" method="post">
                        <div class="form-group">
                            <label>Name</label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Students</label>
                            @Html.EditorFor(x => x.StudentSelections)
                        </div>
                        <div class="form-group">
                            <label>Teachers</label>
                            @Html.EditorFor(x => x.TeacherSelections)
                        </div>
                        <br />
                        <div class="form-group">
                            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                            <input type="submit" name="submit" value="Create" class="btn btn-success float-right" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/AssetManagementPlatform.School/Views/Classroom/Details.cshtml
@using AssetManagementPlatform.SchoolModule.Code.Authentication.Extensions;
@using AssetManagementPlatform.SchoolModule.Entities.Events;
@model AssetManagementPlatform.SchoolModule.ViewModels.Classroom.ClassroomDetailsModel

@{
    string modifiers = "";
    string title = "";
    var permissions = User.GetSchoolUserPermissions();
    @if (!permissions.MarkAbsence)
    {
        modifiers += "disabled";
        title = "You don't have permissions for this";
    }

}
<div class="container-fluid">
    <div class="d-flex flex-column">
        <div class="p-2">
            <div class="card">
                <div class="card-body">
                    <h4>Classroom details</h4>
                    <div class="form-group">
                        <dl>
                            <dt>Class name</dt>
                            <dd>@Model.Name</dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <div class="p-2">
            <div class="card">
                <div class="card-body">
                    <h4>Assigned students</h4>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    Firstname
                                </th>
                                <th>
                                    Lastname
                                </th>
                                <th>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var student in Model.AssignedStudents)
                            {
                                StudentAbsentEvent absentStudentEvent = @Model.AbsentStudentEvents.FirstOrDefault(x => x.AssetId == student.Id);

                                <tr>
                                    <td>
                                        <a asp-controller="Student" asp-action="Details" asp-route-id="@student.Id">@student.FirstName</a>
                                    </td>
                                    <td>
                                        @student.LastName
                                    </td>
                                    <td>
                                        @if (permissions.IsTeacher)
                                        {
                                            @if (absentStudentEvent != null)
                                            {
                                                <a class="btn btn-warning float-right @modifiers" asp-action="UnmarkAbsense" asp-route-studentId="@absentStudentEvent.Id" asp-route-Id="@Model.Id">Unmark absent</a>
                                            }
                                            else
                                            {
                                                <a class="btn btn-warning float-right @modifiers" asp-action="MarkAbsence" asp-route-studentId="@student.Id" asp-route-Id="@Model.Id">Mark absent</a>
                                            }
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="p-2">
            <div class="card">
                <div class="card-body">
                    <h4>Assigned teachers</h4>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    Firstname
                                </th>
                                <th>
                                    Lastname
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var teacher in Model.AssignedTeachers)
                            {
                                <tr>
                                    <td>
                                        <a asp-controller="Teacher" asp-action="Details" asp-route-id="@teacher.Id">@teacher.FirstName</a>
                                    </td>
                                    <td>
                                        @teacher.LastName
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

src/AssetManagementPlatform.School/Views/Classroom/Edit.cshtml
@model AssetManagementPlatform.SchoolModule.ViewModels.Classroom.ClassroomEditModel

<h1>Classes</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Create a class
                </div>
                <div class="card-body">
                    <form asp-action="Edit" method="post">
                        <div class="form-group">
                            <label>Name</label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Students</label>
                            @Html.EditorFor(x => x.StudentSelections)
                        </div>
                        <div class="form-group">
                            <label>Teachers</label>
                            @Html.EditorFor(x => x.TeacherSelections)
                        </div>
                        <br />
                        <div class="form-group">
                            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                            <input type="submit" name="submit" value="Confirm" class="btn btn-success float-right" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

src/AssetManagementPlatform.School/Views/Classroom/Index.cshtml
@using AssetManagementPlatform.SchoolModule.Code.Authentication.Extensions
@model List<AssetManagementPlatform.SchoolModule.Entities.Classroom>
@{
    ViewData["Title"] = "Index";
}
@{
    var permissions = User.GetSchoolUserPermissions();
}
<a class="btn btn-sm btn-success float-right @(permissions.CanCreateClass ? "" : "disabled")" asp-action="Create">Create class</a>
<h1>
    Classes
</h1>
<form method="get" asp-action="Index">
    <div class="input-group">
        @Html.TextBox("query", "", new { @class = "form-control", placeholder = "Search" })
        <span class="input-group-append">
            <button class="btn btn-primary">Search</button>
        </span>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Any())
        {
            @foreach (var classroom in Model)
            {
                <tr>
                    <td>
                        <a asp-action="Details" asp-route-id="@classroom.Id">@classroom.Name</a>
                    </td>
                    <td class="text-nowrap">
                        <a class="btn btn-sm btn-warning @(permissions.CanEditClass ? "" : "disabled")" asp-action="Edit" asp-route-id="@classroom.Id">Edit</a>
                        <a class="btn btn-sm btn-danger @(permissions.CanDeleteClass ? "" : "disabled")" asp-action="Delete" asp-route-id="@classroom.Id">Delete</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <span>No active classes</span>
        }
    </tbody>
</table>